; macros taken from pokered's data/sgb_packets.asm
; names taken from pandocs
; http://gbdev.gg8.se/wiki/articles/SGB_Functions#SGB_Palette_Commands

MACRO sgb_pal_set
	db (SGB_PAL_SET << 3) + 1
	dw PREDEFPAL_\1, PREDEFPAL_\2, PREDEFPAL_\3, PREDEFPAL_\4
	ds 7, 0
ENDM

MACRO sgb_pal01
	db (SGB_PAL01 << 3) + 1
ENDM

MACRO sgb_pal23
	db (SGB_PAL23 << 3) + 1
ENDM

PalPacket_Default:
	sgb_pal_set WHITE, WHITE, WHITE, WHITE

PalPacket_BPSLogo:
	sgb_pal_set BPS_WORDMARK, BPS_LOGO, BPS_LOGO, BPS_LOGO

PalPacket_Copyright:
	sgb_pal_set HUD_TEXT, HUD_TEXT, HUD_TEXT, HUD_TEXT
	sgb_pal_set HUD_TEXT_FADE1, HUD_TEXT_FADE1, HUD_TEXT_FADE1, HUD_TEXT_FADE1
	sgb_pal_set HUD_TEXT_FADE2, HUD_TEXT_FADE2, HUD_TEXT_FADE2, HUD_TEXT_FADE2
	sgb_pal_set WHITE, WHITE, WHITE, WHITE

PalPacket_TitleScreen:
	sgb_pal_set TITLE, HUD_TEXT, HUD_BORDER, TITLE
	sgb_pal_set TITLE_FADE1, HUD_TEXT_FADE1, HUD_BORDER_FADE1, TITLE_FADE1
	sgb_pal_set TITLE_FADE2, HUD_TEXT_FADE2, HUD_BORDER_FADE2, TITLE_FADE2
	sgb_pal_set WHITE, WHITE, WHITE, WHITE

PalPacket_InterFace:
	sgb_pal_set INTERFACE, HUD_TEXT, HUD_BORDER, INTERFACE
	sgb_pal_set INTERFACE_FADE1, HUD_TEXT_FADE1, HUD_BORDER_FADE1, INTERFACE_FADE1
	sgb_pal_set INTERFACE_FADE2, HUD_TEXT_FADE2, HUD_BORDER_FADE2, INTERFACE_FADE2
	sgb_pal_set WHITE, WHITE, WHITE, WHITE

PalPacket_Teamplay:
	sgb_pal_set HUD_BORDER, HUD_BORDER, HUD_BORDER, HUD_BORDER
	sgb_pal_set HUD_BORDER_FADE1, HUD_BORDER_FADE1, HUD_BORDER_FADE1, HUD_BORDER_FADE1
	sgb_pal_set HUD_BORDER_FADE2, HUD_BORDER_FADE2, HUD_BORDER_FADE2, HUD_BORDER_FADE2
	sgb_pal_set WHITE, WHITE, WHITE, WHITE

PalPacket_Gameplay:
	sgb_pal_set GAMEPLAY, HUD_TEXT, HUD_BORDER, GAMEPLAY
	sgb_pal_set GAMEPLAY_FADE1, HUD_TEXT_FADE1, HUD_BORDER_FADE1, GAMEPLAY_FADE1
	sgb_pal_set GAMEPLAY_FADE2, HUD_TEXT_FADE2, HUD_BORDER_FADE2, GAMEPLAY_FADE2
	sgb_pal_set WHITE, WHITE, WHITE, WHITE

PalPacket_EndingSmiloids:
	sgb_pal_set GAMEPLAY, HUD_TEXT, HUD_BORDER, GAMEPLAY
	sgb_pal_set GAMEPLAY_FADE1, HUD_TEXT_FADE1, HUD_BORDER_FADE1, GAMEPLAY_FADE1
	sgb_pal_set GAMEPLAY_FADE2, HUD_TEXT_FADE2, HUD_BORDER_FADE2, GAMEPLAY_FADE2
	sgb_pal_set WHITE, WHITE, WHITE, WHITE

PalPacket_Credits:
	sgb_pal_set INTERFACE, HUD_TEXT, HUD_BORDER, INTERFACE
	sgb_pal_set INTERFACE_FADE1, HUD_TEXT_FADE1, HUD_BORDER_FADE1, INTERFACE_FADE1
	sgb_pal_set INTERFACE_FADE2, HUD_TEXT_FADE2, HUD_BORDER_FADE2, INTERFACE_FADE2
	sgb_pal_set WHITE, WHITE, WHITE, WHITE
